version: "3"
services:
   loquesmitche-application:
      image: platform/loquesmitche:local
      ports:
         - 8088:8080
      environment:
         - FLUIG_URL=${FLUIG_URL:-http://fluig-application:8080}
         - FLUIG_HOST_URL_ADDRESS=${FLUIG_HOST_URL_ADDRESS:-http://fluig.local:8080}
         # database configuration
         - FLUIG_DATABASE_USER=fluig
         - FLUIG_DATABASE_PASSWORD=OLyVu1gIwWmEr
         - FLUIG_DATABASE_URL=jdbc:mysql://demo-dbserver:3306/fluig_demo?useSSL=false
         - FLUIG_DATABASE_DRIVER=com.mysql.jdbc.Driver
         - FLUIG_DATABASE_USER_RO=fluig
         - FLUIG_DATABASE_PASSWORD_RO=OLyVu1gIwWmEr
         - FLUIG_DATABASE_URL_RO=jdbc:mysql://demo-dbserver:3306/fluig_demo?useSSL=false
         # Autenticacao
         - fluig.resource.jwk-enabled=${FLUIG_SECURITY_JWT_ENABLED:-false}
         - fluig.resource.verifier-key=${FLUIG_SECURITY_VERIFIER_KEY:-TesteKey}
         - fluig.resource.signing-key=${FLUIG_SECURITY_SIGNING_KEY:-TesteKey}
         # broker config
         - FLUIG_BROKER_HOST=rabbit-server
         - FLUIG_BROKER_PORT=5672
         - FLUIG_BROKER_USERNAME=guest
         - FLUIG_BROKER_PASSWORD=guest
         # javamelody monitoring
         - JAVAMELODY_ENABLED=true
         - volume=./volume
      networks:
         - platform
      ulimits:
         memlock:
            soft: -1
            hard: -1
         nofile:
            soft: 65536
            hard: 65536
networks:
   platform:
volumes:
   mysql-loquesmitche:
